# Generated by Django 4.0.4 on 2025-02-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
